Map<String, String> imageMapping = {
  'Amiya': 'assets/images/Amiya.jpg',
  '12F': 'assets/images/12F.jpg',
  'Aak': 'assets/images/Aak.jpg',
  'Absinthe': 'assets/images/Absinthe.jpg',
  'Aciddrop': 'assets/images/Aciddrop.jpg',
  'Adnachiel': 'assets/images/Adnachiel.jpg',
  'Akafuyu': 'assets/images/Akafuyu.jpg',
  'Almond': 'assets/images/Almond.jpg',
  'Ambriel': 'assets/images/Ambriel.jpg',
  'Andreana': 'assets/images/Andreana.jpg',
  'Angelina': 'assets/images/Angelina.jpg',
  'Ansel': 'assets/images/Ansel.jpg',
  'Aosta': 'assets/images/Aosta.jpg',
  'April': 'assets/images/April.jpg',
  'Archetto': 'assets/images/Archetto.jpg',
  'Arene': 'assets/images/Arene.jpg',
  'Aroma': 'assets/images/Aroma.jpg',
  'Asbestos': 'assets/images/Asbestos.jpg',
  'Ascalon': 'assets/images/Ascalon.jpg',
  'Ash': 'assets/images/Ash.jpg',
  'Ashlock': 'assets/images/Ashlock.jpg',
  'Astesia': 'assets/images/Astesia.jpg',
  'Astgenne': 'assets/images/Astgenne.jpg',
  'Aurora': 'assets/images/Aurora.jpg',
  'Ch\'en the Holungday': 'assets/images/Ch\'en the Holungday.jpg',
  'Ayerscarpe': 'assets/images/Ayerscarpe.jpg',
  'Bagpipe': 'assets/images/Bagpipe.jpg',
  'Bassline': 'assets/images/Bassline.jpg',
  'Beagle': 'assets/images/Beagle.jpg',
  'Beanstalk': 'assets/images/Beanstalk.jpg',
  'Beeswax': 'assets/images/Beeswax.jpg',
  'Bena': 'assets/images/Bena.jpg',
  'Bibeak': 'assets/images/Bibeak.jpg',
  'Bison': 'assets/images/Bison.jpg',
  'Blacknight': 'assets/images/Blacknight.jpg',
  'Blaze': 'assets/images/Blaze.jpg',
  'Blemishine': 'assets/images/Blemishine.jpg',
  'Blitz': 'assets/images/Blitz.jpg',
  'Blue Poison': 'assets/images/Blue Poison.jpg',
  'Breeze': 'assets/images/Breeze.jpg',
  'Broca': 'assets/images/Broca.jpg',
  'Bryophyta': 'assets/images/Bryophyta.jpg',
  'Bubble': 'assets/images/Bubble.jpg',
  'Cantabile': 'assets/images/Cantabile.jpg',
  'Caper': 'assets/images/Caper.jpg',
  'Cardigan': 'assets/images/Cardigan.jpg',
  'Carnelian': 'assets/images/Carnelian.jpg',
  'Castle-3': 'assets/images/Castle-3.jpg',
  'Cement': 'assets/images/Cement.jpg',
  'Ceobe': 'assets/images/Ceobe.jpg',
  'Ceylon': 'assets/images/Ceylon.jpg',
  'Ch\'en': 'assets/images/Ch\'en.jpg',
  'Chestnut': 'assets/images/Chestnut.jpg',
  'Chiave': 'assets/images/Chiave.jpg',
  'Chongyue': 'assets/images/Chongyue.jpg',
  'Civilight Eterna': 'assets/images/Civilight Eterna.jpg',
  'Click': 'assets/images/Click.jpg',
  'Cliffheart': 'assets/images/Cliffheart.jpg',
  'Coldshot': 'assets/images/Coldshot.jpg',
  'Conviction': 'assets/images/Conviction.jpg',
  'Corroserum': 'assets/images/Corroserum.jpg',
  'Courier': 'assets/images/Courier.jpg',
  'Croissant': 'assets/images/Croissant.jpg',
  'Cuora': 'assets/images/Cuora.jpg',
  'Cutter': 'assets/images/Cutter.jpg',
  'Czerny': 'assets/images/Czerny.jpg',
  'Dagda': 'assets/images/Dagda.jpg',
  'Deepcolor': 'assets/images/Deepcolor.jpg',
  'Degenbrecher': 'assets/images/Degenbrecher.jpg',
  'Delphine': 'assets/images/Delphine.jpg',
  'Diamante': 'assets/images/Diamante.jpg',
  'Dobermann': 'assets/images/Dobermann.jpg',
  'Doc': 'assets/images/Doc.jpg',
  'Dorothy': 'assets/images/Dorothy.jpg',
  'Dur-nar': 'assets/images/Dur-nar.jpg',
  'Durin': 'assets/images/Durin.jpg',
  'Dusk': 'assets/images/Dusk.jpg',
  'Earthspirit': 'assets/images/Earthspirit.jpg',
  'Ebenholz': 'assets/images/Ebenholz.jpg',
  'Ela': 'assets/images/Ela.jpg',
  'Elysium': 'assets/images/Elysium.jpg',
  'Enforcer': 'assets/images/Enforcer.jpg',
  'Erato': 'assets/images/Erato.jpg',
  'Estelle': 'assets/images/Estelle.jpg',
  'Ethan': 'assets/images/Ethan.jpg',
  'Eunectes': 'assets/images/Eunectes.jpg',
  'Executor': 'assets/images/Executor.jpg',
  'Executor the Ex Foedere': 'assets/images/Executor the Ex Foedere.jpg',
  'Exusiai': 'assets/images/Exusiai.jpg',
  'Eyjafjalla': 'assets/images/Eyjafjalla.jpg',
  'Eyjafjalla the Hvít Aska': 'assets/images/Eyjafjalla the Hvít Aska.jpg',
  'FEater': 'assets/images/FEater.jpg',
  'Fang': 'assets/images/Fang.jpg',
  'Fang the Fire-Sharpened': 'assets/images/Fang the Fire-sharpened.jpg',
  'Fartooth': 'assets/images/Fartooth.jpg',
  'Fiammetta': 'assets/images/Fiammetta.jpg',
  'Firewatch': 'assets/images/Firewatch.jpg',
  'Firewhistle': 'assets/images/Firewhistle.jpg',
  'Flamebringer': 'assets/images/Flamebringer.jpg',
  'Flametail': 'assets/images/Flametail.jpg',
  'Flint': 'assets/images/Flint.jpg',
  'Folinic': 'assets/images/Folinic.jpg',
  'Franka': 'assets/images/Franka.jpg',
  'Friston-3': 'assets/images/Friston-3.jpg',
  'Frost': 'assets/images/Frost.jpg',
  'Frostleaf': 'assets/images/Frostleaf.jpg',
  'Fuze': 'assets/images/Fuze.jpg',
  'Gavial': 'assets/images/Gavial.jpg',
  'Gavial the Invincible': 'assets/images/Gavial the Invincible.jpg',
  'Gitano': 'assets/images/Gitano.jpg',
  'Gladiia': 'assets/images/Gladiia.jpg',
  'Glaucus': 'assets/images/Glaucus.jpg',
  'Wiš\'adel': 'assets/images/Wiš\'adel.jpg',



  'default': 'assets/images/Amiya.jpg'
};